In [1]:
import pandas as pd
import numpy as np

In [2]:
filename1 = "Country_intersects_.csv"
grid_df = pd.read_csv(filename1,
                      index_col="Polygon centroid")

grid_df.head()

,Afghanistan - % Intersect,Albania - % Intersect,Algeria - % Intersect,American Samoa - % Intersect,Andorra - % Intersect,Angola - % Intersect,Anguilla - % Intersect,Antigua and Barbuda - % Intersect,Argentina - % Intersect,Armenia - % Intersect,...,Uruguay - % Intersect,Uzbekistan - % Intersect,Vanuatu - % Intersect,Vatican - % Intersect,Venezuela - % Intersect,Vietnam - % Intersect,Wallis and Futuna - % Intersect,Yemen - % Intersect,Zambia - % Intersect,Zimbabwe - % Intersect
Polygon centroid,,,,,,,,,,,,,,,,,,,,,
POINT (-177.5 -87.5),0.0,0.0,0.0,0.0,0,0.0,0,0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0
POINT (-177.5 -82.5),0.0,0.0,0.0,0.0,0,0.0,0,0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0
POINT (-177.5 -77.5),0.0,0.0,0.0,0.0,0,0.0,0,0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0
POINT (-177.5 -72.5),0.0,0.0,0.0,0.0,0,0.0,0,0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0
POINT (-177.5 -67.5),0.0,0.0,0.0,0.0,0,0.0,0,0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
POINT (177.5 67.5),0.0,0.0,0.0,0.0,0,0.0,0,0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0
POINT (177.5 72.5),0.0,0.0,0.0,0.0,0,0.0,0,0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0
POINT (177.5 77.5),0.0,0.0,0.0,0.0,0,0.0,0,0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0
POINT (177.5 82.5),0.0,0.0,0.0,0.0,0,0.0,0,0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0
POINT (177.5 87.5),0.0,0.0,0.0,0.0,0,0.0,0,0,0.0,0.0,...,0.0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,0.0

In [3]:
filename2 = "restoration_potential.csv"
restoration_df = pd.read_csv(filename2,
                             sep=';', 
                             index_col="Country")
restoration_df = restoration_df.rename(columns={"restoration_potential_continuous_TC(Mha),": "restoration_potential_continuous_TC(Mha)"})
restoration_df["restoration_potential_continuous_TC(Mha)"] = restoration_df["restoration_potential_continuous_TC(Mha)"].replace(",", "", regex=True)
restoration_df["restoration_potential_continuous_TC(Mha)"] = pd.to_numeric(restoration_df["restoration_potential_continuous_TC(Mha)"],errors='coerce')
restoration_df = restoration_df.replace(np.nan, 0)

restoration_df.head()

,total_potential_continuous_TC (Mha),restoration_potential_continuous_TC(Mha)
Country,,
Afghanistan,4.253154,2.947729
Albania,1.273294,0.203967
Algeria,3.089146,0.859173
American Samoa,0.009427,0.004936
Andorra,0.011166,0.000716
...,...,...
Vietnam,19.275164,3.122845
Wallis and Futuna,0.002446,0.000483
Yemen,1.029251,0.889427
Zambia,30.001955,10.804289
Zimbabwe,13.584153,7.021692

In [4]:
# restoration potential per grid = (country intersects percent / 100) * restoration potential per country

grid_df=grid_df.div(100)
for i in range(0,217):
    grid_df.iloc[:, i] = grid_df.iloc[:, i] * restoration_df["restoration_potential_continuous_TC(Mha)"][i]
    
grid_df.head()

,Afghanistan - % Intersect,Albania - % Intersect,Algeria - % Intersect,American Samoa - % Intersect,Andorra - % Intersect,Angola - % Intersect,Anguilla - % Intersect,Antigua and Barbuda - % Intersect,Argentina - % Intersect,Armenia - % Intersect,...,Uruguay - % Intersect,Uzbekistan - % Intersect,Vanuatu - % Intersect,Vatican - % Intersect,Venezuela - % Intersect,Vietnam - % Intersect,Wallis and Futuna - % Intersect,Yemen - % Intersect,Zambia - % Intersect,Zimbabwe - % Intersect
Polygon centroid,,,,,,,,,,,,,,,,,,,,,
POINT (-177.5 -87.5),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
POINT (-177.5 -82.5),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
POINT (-177.5 -77.5),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
POINT (-177.5 -72.5),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
POINT (-177.5 -67.5),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
POINT (177.5 67.5),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
POINT (177.5 72.5),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
POINT (177.5 77.5),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
POINT (177.5 82.5),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
POINT (177.5 87.5),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
grid_df["total restoration potential(Mha)"]=grid_df.iloc[:,0:217].sum(axis=1)
isoprene_df = grid_df[["total restoration potential(Mha)"]].copy()

isoprene_df

In [6]:
# Now we need isoprene emission in Tg per year for STOCHEM.
# So Multiply the total restoration potential (Mha) by the isoprene emission (Tgyr-1Mha-1) in certain zone
# I calculated twice for the least and most to get the mean of them.

In [7]:
## Temperate zone (-67.5 ~ -27.5 & 27.5 ~ 47.5)

# The Least isoprene emission (Tgyr-1Mha-1) from "Needleaf Evergreen Temperate Tree": 5.24E+8
least_temperate_df = isoprene_df.copy() # copy to keep the original

# Select row indexes for temperate latitudes
from itertools import chain
temperate = chain(range(4,13), range(23, 28))
for i in temperate:
    for j in range(0,72):
        least_temperate_df.iloc[[i+36*j][0]] *= 5.24E+8
# Change to 0 for the rest latitudes (because there will be no additional isoprene emission if I just plant in temperate zone)
not_temperate = chain(range(0,4), range(13,23), range(28,36))
for i in not_temperate:
    for j in range(0,72):
        least_temperate_df.iloc[[i+36*j][0]] *= 0
least_temperate_df = least_temperate_df.rename(columns={"total restoration potential(Mha)": "least isoprene emission (Tg/yr)"})

# The Most isoprene emission (Tgyr-1Mha-1) from "Broadleaf Evergreen Temperate Tree": 1.47E+10
most_temperate_df = isoprene_df.copy()

# Select row indexes for temperate latitudes
temperate = chain(range(4,13), range(23, 28))
for i in temperate:
    for j in range(0,72):
        most_temperate_df.iloc[[i+36*j][0]] *= 1.47E+10
# Change to 0 for the rest latitudes
not_temperate = chain(range(0,4), range(13,23), range(28,36))
for i in not_temperate:
    for j in range(0,72):
        most_temperate_df.iloc[[i+36*j][0]] *= 0
most_temperate_df = most_temperate_df.rename(columns={"total restoration potential(Mha)": "most isoprene emission (Tg/yr)"})
 
#Merge two dataframes with the same index column
temperate_df = pd.concat([least_temperate_df, most_temperate_df], axis=1)
temperate_df["mean isoprene emission (Tg/yr)"] = temperate_df.mean(axis=1)
temperate_df

,least isoprene emission (Tg/yr),most isoprene emission (Tg/yr),mean isoprene emission (Tg/yr)
Polygon centroid,,,
POINT (-177.5 -87.5),0.0,0.0,0.0
POINT (-177.5 -82.5),0.0,0.0,0.0
POINT (-177.5 -77.5),0.0,0.0,0.0
POINT (-177.5 -72.5),0.0,0.0,0.0
POINT (-177.5 -67.5),0.0,0.0,0.0
...,...,...,...
POINT (177.5 67.5),0.0,0.0,0.0
POINT (177.5 72.5),0.0,0.0,0.0
POINT (177.5 77.5),0.0,0.0,0.0
POINT (177.5 82.5),0.0,0.0,0.0
POINT (177.5 87.5),0.0,0.0,0.0

In [8]:
## Tropical zone (-22.5 ~ 22.5)

# The Least isoprene emission (Tgyr-1Mha-1) from "Broadleaf Deciduous Tropical Tree": 3.93E+10
least_tropical_df = isoprene_df.copy()

# Select row indexes for tropical latitudes
for i in range(13,23):
    for j in range(0,72):
        least_tropical_df.iloc[[i+36*j][0]] *= 3.93E+10
# Change to 0 for the rest latitudes
not_tropical = chain(range(0,13), range(23,36))
for i in not_tropical:
    for j in range(0,72):
        least_tropical_df.iloc[[i+36*j][0]] *= 0
least_tropical_df = least_tropical_df.rename(columns={"total restoration potential(Mha)": "least isoprene emission (Tg/yr)"})

# The Most isoprene emission (Tgyr-1Mha-1) from "Broadleaf Evergreen Tropical Tree": 4.46E+10
most_tropical_df = isoprene_df.copy()

# Select row indexes for tropical latitudes
for i in range(13,23):
    for j in range(0,72):
        most_tropical_df.iloc[[i+36*j][0]] *= 4.46E+10
# Change to 0 for the rest latitudes
not_tropical = chain(range(0,13), range(23,36))
for i in not_tropical:
    for j in range(0,72):
        most_tropical_df.iloc[[i+36*j][0]] *= 0
most_tropical_df = most_tropical_df.rename(columns={"total restoration potential(Mha)": "most isoprene emission (Tg/yr)"})
 
#Merge two dataframes with the same index column
tropical_df = pd.concat([least_tropical_df, most_tropical_df], axis=1)
tropical_df["mean isoprene emission (Tg/yr)"] = tropical_df.mean(axis=1)
tropical_df

,least isoprene emission (Tg/yr),most isoprene emission (Tg/yr),mean isoprene emission (Tg/yr)
Polygon centroid,,,
POINT (-177.5 -87.5),0.0,0.0,0.0
POINT (-177.5 -82.5),0.0,0.0,0.0
POINT (-177.5 -77.5),0.0,0.0,0.0
POINT (-177.5 -72.5),0.0,0.0,0.0
POINT (-177.5 -67.5),0.0,0.0,0.0
...,...,...,...
POINT (177.5 67.5),0.0,0.0,0.0
POINT (177.5 72.5),0.0,0.0,0.0
POINT (177.5 77.5),0.0,0.0,0.0
POINT (177.5 82.5),0.0,0.0,0.0
POINT (177.5 87.5),0.0,0.0,0.0

In [9]:
## Boreal zone (52.5 ~ 62.5)

# The Least isoprene emission (Tgyr-1Mha-1) from "Needleleaf Deciduous Boreal Tree": 3.22E+5
least_boreal_df = isoprene_df.copy()

# Select row indexes for boreal latitudes
for i in range(28,31):
    for j in range(0,72):
        least_boreal_df.iloc[[i+36*j][0]] *= 3.22E+5
# Change to 0 for the rest latitudes
not_boreal = chain(range(0,28), range(31,36))
for i in not_boreal:
    for j in range(0,72):
        least_boreal_df.iloc[[i+36*j][0]] *= 0
least_boreal_df = least_boreal_df.rename(columns={"total restoration potential(Mha)": "least isoprene emission (Tg/yr)"})

# The Most isoprene emission (Tgyr-1Mha-1) from "Broadleaf Deciduous Boreal Tree": 5.27E+9
most_boreal_df = isoprene_df.copy()

# Select row indexes for boreal latitudes
for i in range(28,31):
    for j in range(0,72):
        most_boreal_df.iloc[[i+36*j][0]] *= 5.27E+9
# Change to 0 for the rest latitudes
not_boreal = chain(range(0,28), range(31,36))
for i in not_boreal:
    for j in range(0,72):
        most_boreal_df.iloc[[i+36*j][0]] *= 0
most_boreal_df = most_boreal_df.rename(columns={"total restoration potential(Mha)": "most isoprene emission (Tg/yr)"})

#Merge two dataframes with the same index column
boreal_df = pd.concat([least_boreal_df, most_boreal_df], axis=1)
boreal_df["mean isoprene emission (Tg/yr)"] = boreal_df.mean(axis=1)
boreal_df

,least isoprene emission (Tg/yr),most isoprene emission (Tg/yr),mean isoprene emission (Tg/yr)
Polygon centroid,,,
POINT (-177.5 -87.5),0.0,0.0,0.0
POINT (-177.5 -82.5),0.0,0.0,0.0
POINT (-177.5 -77.5),0.0,0.0,0.0
POINT (-177.5 -72.5),0.0,0.0,0.0
POINT (-177.5 -67.5),0.0,0.0,0.0
...,...,...,...
POINT (177.5 67.5),0.0,0.0,0.0
POINT (177.5 72.5),0.0,0.0,0.0
POINT (177.5 77.5),0.0,0.0,0.0
POINT (177.5 82.5),0.0,0.0,0.0
POINT (177.5 87.5),0.0,0.0,0.0

In [10]:
## Arctic zone (67.5 ~ 87.5)

# The isoprene emission from "Arctic C3 Grass": 9.7E+7
arctic_df = isoprene_df.copy()

# Select row indexes for arctic latitudes
for i in range(31,36):
    for j in range(0,72):
        arctic_df.iloc[[i+36*j][0]] *= 9.7E+7
# Change to 0 for the rest latitudes
for i in range(0,31):
    for j in range(0,72):
        arctic_df.iloc[[i+36*j][0]] *= 0
arctic_df = arctic_df.rename(columns={"total restoration potential(Mha)": "isoprene emission (Tg/yr)"})
arctic_df

                      isoprene emission (Tg/yr)
Polygon centroid
POINT (-177.5 -87.5)               0.000000e+00
POINT (-177.5 -82.5)               0.000000e+00
POINT (-177.5 -77.5)               0.000000e+00
POINT (-177.5 -72.5)               0.000000e+00
POINT (-177.5 -67.5)               0.000000e+00
...                                         ...
POINT (177.5 67.5)                 1.131908e+08
POINT (177.5 72.5)                 3.128402e+06
POINT (177.5 77.5)                 0.000000e+00
POINT (177.5 82.5)                 0.000000e+00
POINT (177.5 87.5)                 0.000000e+00

[2592 rows x 1 columns]

In [11]:
# Dataframe to Excel
with pd.ExcelWriter("Isoprene Emission: Each Region.xlsx") as writer:  
    temperate_df.to_excel(writer, sheet_name = "Temperate")
    tropical_df.to_excel(writer, sheet_name = "Tropical")
    boreal_df.to_excel(writer, sheet_name = "Boreal")
    arctic_df.to_excel(writer, sheet_name = "Arctic")

In [12]:
## This time, I will assume that I plant trees with minimum isoprene emissions for all regions.
minimum_df = isoprene_df.copy()

# Temperate zone (-67.5 ~ -27.5 & 27.5 ~ 47.5): "Needleaf Evergreen Temperate Tree" (5.24E+8)
temperate = chain(range(4,13), range(23, 28))
for i in temperate:
    for j in range(0,72):
        minimum_df.iloc[[i+36*j][0]] *= 5.24E+8

# Tropical zone (-22.5 ~ 22.5): "Broadleaf Deciduous Tropical Tree" (3.93E+10)
for i in range(13,23):
    for j in range(0,72):
        minimum_df.iloc[[i+36*j][0]] *= 3.93E+10
        
# Boreal zone (52.5 ~ 62.5): "Needleleaf Deciduous Boreal Tree" (3.22E+5)
for i in range(28,31):
    for j in range(0,72):
        minimum_df.iloc[[i+36*j][0]] *= 3.22E+5
        
# Arctic zone (67.5 ~ 87.5): "Arctic C3 Grass" (9.70E+7)
for i in range(31,36):
    for j in range(0,72):
        minimum_df.iloc[[i+36*j][0]] *= 9.70E+7
# Change to 0 for the rest latitudes
for i in range(0,4):
    for j in range(0,72):
        minimum_df.iloc[[i+36*j][0]] *= 0
        
minimum_df = minimum_df.rename(columns={"total restoration potential(Mha)": "minimum isoprene emission (Tg/yr)"})
minimum_df

                      minimum isoprene emission (Tg/yr)
Polygon centroid
POINT (-177.5 -87.5)                       0.000000e+00
POINT (-177.5 -82.5)                       0.000000e+00
POINT (-177.5 -77.5)                       0.000000e+00
POINT (-177.5 -72.5)                       0.000000e+00
POINT (-177.5 -67.5)                       0.000000e+00
...                                                 ...
POINT (177.5 67.5)                         1.131908e+08
POINT (177.5 72.5)                         3.128402e+06
POINT (177.5 77.5)                         0.000000e+00
POINT (177.5 82.5)                         0.000000e+00
POINT (177.5 87.5)                         0.000000e+00

[2592 rows x 1 columns]

In [13]:
## Similarly, I will assume that I plant trees with maximum isoprene emissions for all regions.
maximum_df = isoprene_df.copy()

# Temperate zone (-67.5 ~ -27.5 & 27.5 ~ 47.5): "Broadleaf Evergreen Temperate Tree" (1.47E+10)
temperate = chain(range(4,13), range(23, 28))
for i in temperate:
    for j in range(0,72):
        maximum_df.iloc[[i+36*j][0]] *= 1.47E+10

# Tropical zone (-22.5 ~ 22.5): "Broadleaf Evergreen Tropical Tree" (4.46E+10)
for i in range(13,23):
    for j in range(0,72):
        maximum_df.iloc[[i+36*j][0]] *= 4.46E+10
        
# Boreal zone (52.5 ~ 62.5): "Broadleaf Deciduous Boreal Tree" (5.27E+9)
for i in range(28,31):
    for j in range(0,72):
        maximum_df.iloc[[i+36*j][0]] *= 5.27E+9
        
# Arctic zone (67.5 ~ 87.5): "Arctic C3 Grass" (9.70E+7)
for i in range(31,36):
    for j in range(0,72):
        maximum_df.iloc[[i+36*j][0]] *= 9.70E+7
# Change to 0 for the rest latitudes
for i in range(0,4):
    for j in range(0,72):
        maximum_df.iloc[[i+36*j][0]] *= 0
        
maximum_df = maximum_df.rename(columns={"total restoration potential(Mha)": "maximum isoprene emission (Tg/yr)"})
maximum_df

                      maximum isoprene emission (Tg/yr)
Polygon centroid
POINT (-177.5 -87.5)                       0.000000e+00
POINT (-177.5 -82.5)                       0.000000e+00
POINT (-177.5 -77.5)                       0.000000e+00
POINT (-177.5 -72.5)                       0.000000e+00
POINT (-177.5 -67.5)                       0.000000e+00
...                                                 ...
POINT (177.5 67.5)                         1.131908e+08
POINT (177.5 72.5)                         3.128402e+06
POINT (177.5 77.5)                         0.000000e+00
POINT (177.5 82.5)                         0.000000e+00
POINT (177.5 87.5)                         0.000000e+00

[2592 rows x 1 columns]

In [14]:
## Finally, I will calculate the mean of two.
# To do this easily, I will merge two database in one.
mean_df = pd.concat([minimum_df, maximum_df], axis=1)
mean_df["mean isoprene emission (Tg/yr)"] = mean_df.mean(axis=1)
mean_df

,minimum isoprene emission (Tg/yr),maximum isoprene emission (Tg/yr),mean isoprene emission (Tg/yr)
Polygon centroid,,,
POINT (-177.5 -87.5),0.000000e+00,0.000000e+00,0.000000e+00
POINT (-177.5 -82.5),0.000000e+00,0.000000e+00,0.000000e+00
POINT (-177.5 -77.5),0.000000e+00,0.000000e+00,0.000000e+00
POINT (-177.5 -72.5),0.000000e+00,0.000000e+00,0.000000e+00
POINT (-177.5 -67.5),0.000000e+00,0.000000e+00,0.000000e+00
...,...,...,...
POINT (177.5 67.5),1.131908e+08,1.131908e+08,1.131908e+08
POINT (177.5 72.5),3.128402e+06,3.128402e+06,3.128402e+06
POINT (177.5 77.5),0.000000e+00,0.000000e+00,0.000000e+00
POINT (177.5 82.5),0.000000e+00,0.000000e+00,0.000000e+00
POINT (177.5 87.5),0.000000e+00,0.000000e+00,0.000000e+00

In [15]:
# Dataframe to Excel
mean_df.to_excel("Isoprene Emission: All Regions.xlsx")